name: Mantener App Activa

on:
  schedule:
    # Se ejecuta automáticamente cada 12 horas
    - cron: '0 */12 * * *'
  # Permite ejecutar la prueba manualmente desde GitHub
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a la app de Streamlit
        run: |
          curl -s -o /dev/null -w "Status Code: %{http_code}\n" https://confesionario-shisqueic.streamlit.app/
